#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "material"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    windows_index_type = 3
    enable_tabline_filetype_icon = true
    # status line options
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    buffer_index_type = 4
    statusline_separator = "arrow"
    statusline_iseparator = "bar"
    enable_statusline_mode = true
    statusline_unicode_symbols = true
    # idents & tabs
    default_indent = 4
    expand_tab = true
    # bootstrap
    bootstrap_before = "xstatervim#before"
    bootstrap_after = "xstatervim#after"
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    # autocomplete
    autocomplete_method = "coc"
    # checkers
    lint_on_the_fly = true
    # file tree
    enable_filetree_gitstatus = true

[[layers]]
name = "colorscheme"

[[layers]]
name = "fzf"

[[layers]]
name = "git"

[[layers]]
name = "VersionControl"

[[layers]]
name = "core#statusline"

[[layers]]
name = "core"
enabe_smooth_scrolling = true

[[layers]]
name = "default"

[[layers]]
name = "format"

# Install GNU Global
# Install Universal ctags
# [[layers]]
# name = "gtags"
# gtagslabel = "new-ctags"

# Enable autocomplete layer
[[layers]]
name = "autocomplete"
auto_completion_return_key_behavior = "smart"
auto_completion_tab_key_behavior = "cycle"

[[layers]]
name = "checkers"

[[layers]]
name = "lang#toml"

[[layers]]
name = "lang#vim"

[[layers]]
name = "lang#rust"

[[layers]]
name = "lsp"
filetype = ["rust"]


